config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :registers

  resources :users, only: [ :index, :update, :destroy ]
  put "/users", to: "users#update", as: :update_user_without_id_for_jwt

  resources :foods, only: [ :create ]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "homepages#index"
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  allow_unauthenticated_access
  skip_forgery_protection
  skip_before_action :authenticate_request

  def new
    @user = User.new
  end

  def create
    @user = User.new(userparams)

    if @user.save
      respond_to do |format|
        format.json do
          render json: { Success: true, Message: "Account Created Succesfully" }, status: :created
        end
        format.html do
          redirect_to session_path
        end
      end
    else
      respond_to do |format|
        format.json { render json: { Success: false, Message: @user.errors }, status: :unauthorized }
        format.html do
          redirect_to new_registers_path, alert: "Username / Email already used, please use another email address"
        end
      end
    end
  end

  def show
    head :no_content
  end

  private

  def userparams
    params.permit(:username, :email_address, :password)
  end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if alert = flash[:alert] %>
    <p
      class="
        py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block
      "
      id="alert"
    ><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Register</h1>

  <%= form_with url: registers_url, class: "contents" do |form| %>

    <div class="my-5">
      <%= form.text_field :username,
                      required: true,
                      autofocus: true,
                      autocomplete: "username",
                      placeholder: "Username",
                      value: params[:username],
                      class:
                        "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.email_field :email_address,
                       required: true,
                       autofocus: true,
                       autocomplete: "username",
                       placeholder: "Email Address",
                       value: params[:email_address],
                       class:
                         "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.password_field :password,
                          required: true,
                          autocomplete: "current-password",
                          placeholder: "Password",
                          maxlength: 72,
                          class:
                            "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
      <div class="inline">
        <%= form.submit "Register",
                    class:
                      "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
      </div>

      <div class="mt-4 text-sm text-gray-500 sm:mt-0">
        <%= link_to "Already have an account?",
        new_session_path,
        class: "text-gray-700 underline hover:no-underline" %>
      </div>
    </div>
  <% end %>
</div>